# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "otterhub"
compatibility_date = "2026-01-01"
pages_build_output_dir = "frontend/out"

# [build]
# command = "cd frontend && npm install && npm run build"

[observability]
enabled = true